spring:
  application:
    name: testRabbitMQ
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5673}
    username: ${RABBIT_USERNAME:admin}
    password: ${RABBIT_PASSWORD:admin}

server:
  port: 8181

application:
  queue:
    default-queue-1: default-queue1
    default-queue-2: default-queue2
    direct-queue-1: direct-queue1
    direct-queue-2: direct-queue2
    fanout-queue-1: fanout-q1
    fanout-queue-2: fanout-q2
    fanout-queue-3: fanout-q3
    headers-queue-1: headers-q1
    headers-queue-2: headers-q2
    headers-queue-3: headers-q3
    topic-queue-1: topic-q1
    topic-queue-2: topic-q2
    topic-queue-3: topic-q3
    exception-queue: exception-queue
    dead-letters-queue: dead-letters-queue
  exchange:
    fanout-exchange: test-fanout
    headers-exchange: test-headers
    topic-exchange: test-topic
    direct-exchange1: test-direct1
    direct-exchange2: test-direct2
    dead-exchange: test-dead